spring:
  #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_master
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mx123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: web-tlias0916