spring:
  #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mx123456

  #mybatis配置
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true

      #spring事务管理日志
      logging:
        level:
          org.springframework.jdbc.support.JdbcTransactionManager: debug


