spring:
  #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_master
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Roze
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true

